# Generated by Django 5.1.6 on 2025-02-24 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_book_table_alter_borrowedbook_table_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Books',
        ),
        migrations.RenameModel(
            old_name='BorrowedBook',
            new_name='BorrowedBooks',
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
